### ISSUE TITLE
Error GET/POST requests missing with Lambda Handler

### ISSUE THREAD

**Issue by nenti** [apollographql/graphql-server#332]
I'm running into an Error running this plugin with a serverless setup as follow:
```
functions:
  api:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: POST
        cors: true
        integration: lambda
    - http:
        path: graphql
        method: GET
        cors: true
        integration: lambda
```

There seems to be missing a proper handling of API-Gateway + Lambda setup.
