### ISSUE TITLE
Lambda server : Internal server error

### ISSUE THREAD

**Issue by chrishiste** [apollographql/graphql-server#333]
Hello, I'm trying to use the lambda server but it doesn't work, when I go on my API Gateway url it sends back : 
```
{"message": "Internal server error"}
```

Here is my server.js file. It's really basic so I don't think something is wrong here but maybe. I use babel before uploading to lambda.
```js
import server from 'graphql-server-lambda';
import graphqlTools from 'graphql-tools';

const schema = `
type Query {
    hello: String
}
`;

const resolver = {
  Query: {
    hello: () => 'Hello World',
  },
};

const myGraphQLSchema = graphqlTools.makeExecutableSchema({
  typeDefs: schema,
  resolvers: resolver,
});

exports.graphqlHandler =  server.graphqlLambda({ schema: myGraphQLSchema });
exports.graphiqlHandler = server.graphiqlLambda({ endpointURL: '/dev/graphql' });
```

The logs in AWS say :
```
Execution failed due to configuration error: Malformed Lambda proxy response
```

I'm almost sure my API Gateway is well configured because I tried using lambda-graphql (https://www.npmjs.com/package/lambda-graphql) and everything worked like a charm. But thing is I really want to use an apollo server.

I'm using serverless and enabling CORS so it shouldn't be a problem.
```yaml
functions:
  server:
    handler: server.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true
  ide:
    handler: server.graphiqlHandler
    events:
      - http:
          path: graphiql
          method: get
          cors: true
```

Any idea what I'm doing wrong ? THANKS <3
