### ISSUE TITLE
[lambda] GraphiQL "Forbidden" response message

### ISSUE THREAD

**Issue by jagi** [apollographql/graphql-server#367]
I'm having a problem with running GraphiQL on AWS lambda. When I make a query I receive
```
{
  "message": "Forbidden"
}
```
as a response.

Response Headers
```
content-length:24
content-type:application/json
date:Tue, 18 Apr 2017 18:36:56 GMT
status:403
via:1.1 0e8771af788075ec65db839e649274c4.cloudfront.net (CloudFront)
x-amz-cf-id:AWV24_u97BrxUf5IEtuE0rdBOKh_xoijNy79pbSKpsRlzblF3VkTdA==
x-amzn-errortype:ForbiddenException
x-amzn-requestid:ffcea8fc-2465-11e7-9f34-1f26a4ebd9d4
x-cache:Error from cloudfront
```

The problem is only with GraphiQL. The GraphQL endpoint is working correctly. It's hard to tell what's a source of the problem because there are no CloudWatch logs. It looks like lambda function is never called.

I'm using [Serverless](https://serverless.com) to deploy lambda functions, but I don't think it's a case here as the GraphQL endpoint is working correctly. When I'm testing GraphiQL endpoint locally using `serverless-offline` everything works as expected.

Could you give me some tip on how to investigate this problem? Might it be a problem with this package or is it a problem with AWS?

**Comment by soda0289** [comment]
If there are no CloudWatch logs you are correct to assume that the lambda function is not running. You can always run the lambda function from the API Gateway console to make sure it is handling the request correctly.

A forbidden response is the default response when the API Gateway has not been configured for that endpoint. Could be a typo or using the wrong HTTP method. Take a look at the API Gateway console and ensure the endpoints are correct. GraphiQL should be using the GET method.

You can post your serverless config and I can take a look or check out this known working config:
https://github.com/apollographql/graphql-server/issues/332#issuecomment-288417312

**Comment by jagi** [comment]
@soda0289 thanks for the fast reply. Testing lambda function from the API Gateway console is not needed as I said GraphQL endpoint works correctly. However, I did test for POST and GET requests and both work properly. The only problem is that when request comes from the GraphiQL, then it does not work.

My SLS config is following:
```yaml
  GraphQL:
    handler: handlers.graphql
    memory: 512
    timeout: 300
    events:
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true
  GraphiQL:
    handler: handlers.graphiql
    memory: 512
    timeout: 300
    events:
      - http:
          path: graphiql
          method: get
          cors: true
      - http:
          path: graphiql
          method: post
          cors: true
```
and `handlers.js`
```js
const server = require('graphql-server-lambda');
module.exports.graphql = function(event, context, callback)  {
  const callbackFilter = (err, output) => {
    output.headers['Access-Control-Allow-Origin'] = '*';
    callback(err, output);
  };
  const handler = server.graphqlLambda({
    schema: require('./lib/schema')
  });
  return handler(event, context, callbackFilter);
};
module.exports.graphiql = server.graphiqlLambda({
  endpointURL: '/graphql'
});
```

Btw. I had to define both POST and GET methods for GraphiQL because without POST it was not working. It was complaining about lack of the POST method.
